### ISSUE TITLE
OBS freezes after adding the plugin

### ISSUE THREAD

**Issue by ASchneiderBR** [norihiro/obs-main-view-source#4]
Hello!

Since the last couple of releases, I'm unable to add this plugin to my OBS without it crashing after a few seconds.

Here's a video showing it, it happens 100% of the time without showing anything in the log:

https://user-images.githubusercontent.com/25224882/183920176-c400fcb7-d213-49bd-8d75-db7b97fbb66b.mp4

Thank you.

**Comment by norihiro** [comment]
I cannot reproduce the bug even though adding browser source and move transition as it is appearing on your log window.
Would you provide log file so that I can try to make same setup of plugins, scenes, sources, and filters.

**Comment by ASchneiderBR** [comment]
No problem! Thanks.

[2022-08-10 10-54-17.txt](https://github.com/norihiro/obs-main-view-source/files/9301368/2022-08-10.10-54-17.txt)

**Comment by norihiro** [comment]
I noticed `Output Source` provided by downstream keyer does almost same thing as this plugin. If Output Source is sufficient for your purpose, I would recommend Output Source since it has been maintained much longer than this plugin.

**Comment by ASchneiderBR** [comment]
Hello @norihiro! Thanks for the reply. I've added an output source using NDI, which is very expensive since it goes through the localhost network and "show itself" in it. Downstream keyer is a plugin made by Exeldro, that overlays something in front of the output, on all scenes and transitions. Sorry, not sure if I got your point... I really like the idea of your plugin, it would be great to not use NDI for this (it also exposes an unnecessary NDI stream over your network). Thanks for your work here :)

**Comment by norihiro** [comment]
> Downstream keyer is a plugin made by Exeldro, that overlays something in front of the output, on all scenes and transitions.

You are right. However, that plugin bundles a source named `Output Source`. When looking at the source code, I noticed Output Source is quite similar to Main View Source.

**Comment by ASchneiderBR** [comment]
Not sure if it is active or not, when I add it, it only has this channel settings and shows nothing...

![image](https://user-images.githubusercontent.com/25224882/183963809-ab0e7ad9-0e73-4d5d-9329-c4d517bc4c67.png)

**Comment by norihiro** [comment]
Output Source will only show contents when it's added to a scene that is not displayed on the main view itself to avoid recursive rendering.

**Comment by ASchneiderBR** [comment]
Wow! Now I understand what this source does, just amazing! I could reduce a hole 3ms from my render frame time just by using it and disabling NDI, just incredible. Thank you, I'll use Exeldro's plugin for this use case. Have a great day!
